blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, blog_toggle_is_published

from blog.apps import BlogConfig
app_name = BlogConfig.name

urlpatterns = [
    path('blog_form/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_form/<int:pk>', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_toggle_is_published/<int:pk>', blog_toggle_is_published, name='blog_toggle_is_published')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from utils.utils import generate_filename_blog


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name="Наименование")
    slug = models.CharField(max_length=200, verbose_name="slug", blank=True, null=True)
    body = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(upload_to=generate_filename_blog, verbose_name="Превью", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return f"{self.title}, {self.slug}"

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ['title', 'created_at', 'is_published', 'views_count']

        permissions = [
                ('can_control_blog', 'Может управлять блогами'),
            ]

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog
from utils.utils import send_mail_async


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'is_published')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    paginate_by = 4

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1

        # Если количество просмотров достигло 100, то отправляем сообщение на почту
        if self.object.views_count == 100:
            send_mail_async('Сообщение с сайта', f'Ваш блог {self.object.title} достиг 100 просмотров',
                            ["churilov.e.a@yandex.ru"], )

        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'slug', 'body', 'preview', 'is_published')
    login_url = reverse_lazy('users:login')

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser or user.has_perm("blog.can_control_blog"):
            return super().get_form_class()

        raise PermissionDenied


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    login_url = reverse_lazy('users:login')


@login_required(login_url=reverse_lazy('users:login'))
def blog_toggle_is_published(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.is_published = not blog.is_published
    blog.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">Хотите удалить?</h3>
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="card-body">
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-primary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                <h4 class="my-0 font-weight-normal">{{ object.slug }}</h4>
            </div>
            <div class="card-body">
                <img class="rounded mx-auto d-block img-fluid" src="{{ object.preview | make_media_path }}"
                     alt="Изображение продукта">
                <p class="mt-3 mb-4 text-start m-3">{{ object.body }}</p>
                <p class="mt-3 mb-4 text-start m-3">Дата создания: {{ object.created_at }}</p>
                {% if perms.blog.can_control_blog %}
                {% if object.is_published %}
                <a class="btn btn-warning"
                   href="{% url 'blog:blog_toggle_is_published' object.pk %}">Снять с публикации</a>
                {% else %}
                <a class="btn btn-success"
                   href="{% url 'blog:blog_toggle_is_published' object.pk  %}">Опубликовать</a>
                {% endif %}
                {% endif %}
                <p class="mt-3 mb-4 text-start m-3">Просмотров: {{ object.views_count }}</p>
                {% if perms.blog.can_control_blog %}
                <a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-primary">Редактировать</a>
                <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Добавьте блог</h1>
</div>
<div class="row text-start">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Форма для добавления нового блога</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                            Обновить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блоги</h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_create'%}">Создать</a>
    <div class="row text-center">
        <div class="row text-center">
            {% for blog in page_obj %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p class="mt-3 mb-4 text-start m-3">{{ blog.body|truncatechars:200 }}</p>
                        <p class="card-title pricing-card-title">{{ blog.created_at}} ₽</p>
                        <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                           href="{% url 'blog:blog_detail' blog.pk %}">Подробнее</a>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div id="pages" align="center">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}

                <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endblock%}