blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, blog_toggle_is_published

from blog.apps import BlogConfig
app_name = BlogConfig.name

urlpatterns = [
    path('blog_form/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_form/<int:pk>', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_toggle_is_published/<int:pk>', blog_toggle_is_published, name='blog_toggle_is_published')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, ProfilePasswordRestoreView, \
    password_restore_success

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/user_login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm/<str:token>/', email_verification, name='confirm'),
    path('password_restore/', ProfilePasswordRestoreView.as_view(), name='password_restore'),
    path('password_restore_success/', password_restore_success, name='password_restore_success'),
]

users/models.py
from django.apps import apps
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_countries.data import COUNTRIES
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

from utils.utils import generate_filename_user_avatar
from django.utils.translation import gettext_lazy as _

# Пример команды для создания суперпользователя (Обязательно через --email)
# python manage.py createsuperuser --email test@test.ru
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("Email должен быть указан")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    objects = UserManager()

    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone_number = PhoneNumberField(verbose_name="Номер телефона", blank=True, null=True)
    avatar = models.ImageField(upload_to=generate_filename_user_avatar, verbose_name="Аватар", blank=True, null=True)
    country = CountryField(_(u'Country'), choices=COUNTRIES,  blank_label="(Выберете страну)")

    token = models.CharField(max_length=255, verbose_name="token", blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

    def get_email(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import HiddenInput, forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone_number', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = HiddenInput()


class ProfilePasswordRestoreForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = HiddenInput()

    def clean(self):
        # Намеренная заглушка, чтобы clean-метод не ругался на существующий адрес
        pass

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким адресом электронной почты не найден.')
        return email

users/views.py
import secrets
from time import sleep

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm, ProfilePasswordRestoreForm
from users.models import User
from utils.utils import send_mail_async


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/user_register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(32)
        user.token = token
        host = self.request.get_host()
        url = f"http://{host}/users/confirm/{token}/"
        send_mail_async("Подтверждение почты", f"Для подтверждения вашей почты перейдите по ссылке ниже!\n{url}",
                        [user.email])
        user.save()
        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class ProfilePasswordRestoreView(CreateView):
    model = User
    form_class = ProfilePasswordRestoreForm
    template_name = 'users/user_password_restore.html'
    success_url = reverse_lazy('users:password_restore_success')

    def form_valid(self, form):
        # Если from valid, то намеренно не вызываем родительский метод, чтобы не было попытки сохранения в БД!!!
        email = form.cleaned_data['email']
        user = get_object_or_404(User, email=email)
        password = User.objects.make_random_password()
        user.set_password(password)
        user.save(update_fields=['password'])

        send_mail_async("Новый пароль", f"Ваш новый пароль!\n{password}",
                        [user.email])

        return redirect(self.success_url)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def password_restore_success(request):
    return render(request, 'users/user_password_restore_success.html')

users/templates/users/user_form.html
{% extends 'catalog/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Форма профиля</h1>
</div>
<div class="row text-start">
    <form method="post" action="" class="row" enctype="multipart/form-data">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Профиль</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock%}

users/templates/users/user_login.html
{% extends 'catalog/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Форма входа</h1>
</div>
<div class="row text-start">
    <form method="post" action="" class="row" enctype="multipart/form-data">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Вход</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Войти</button>
                    <a href="{% url 'users:password_restore' %}" class="btn btn-lg btn-block btn-outline-primary">Восстановить пароль</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock%}

users/templates/users/user_password_restore.html
{% extends 'catalog/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Форма восстановления пароля</h1>
</div>
<div class="row text-start">
    <form method="post" action="" class="row" enctype="multipart/form-data">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Восстановление пароля</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Восстановить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock%}

users/templates/users/user_password_restore_success.html
{% extends 'catalog/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Письмо с новым паролем отправлено на вашу почту</h1>
</div>
<div class="row text-start">

</div>
{% endblock%}

users/templates/users/user_register.html
{% extends 'catalog/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Форма регистрации</h1>
</div>
<div class="row text-start">
    <form method="post" action="" class="row" enctype="multipart/form-data">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Регистрация</h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Регистрация</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock%}