blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, blog_toggle_is_published

from blog.apps import BlogConfig
app_name = BlogConfig.name

urlpatterns = [
    path('blog_form/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_form/<int:pk>', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_toggle_is_published/<int:pk>', blog_toggle_is_published, name='blog_toggle_is_published')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.views import ContactPageView, ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView, \
    ProductDeleteView, CategoryListView

from catalog.apps import CatalogConfig
app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactPageView.as_view(), name='contact_view'),
    path('create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('update/<int:pk>', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),

    path('categories/', CategoryListView.as_view(), name='category_list')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User
from utils.utils import generate_filename_product


# Рабочая команда для фикстур
# python -Xutf8 manage.py dumpdata catalog --indent=2 --exclude auth.permission --exclude contenttypes -o catalog/fixtures/data.json


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")
    preview = models.ImageField(upload_to=generate_filename_product, verbose_name="Превью", blank=True, null=True)
    category = models.ForeignKey(to="Category", on_delete=models.SET_NULL, verbose_name="Категория", blank=True,
                                 null=True, related_name="products")
    price_per_purchase = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена за покупку")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")

    owner = models.ForeignKey(User, verbose_name="Владелец товара", help_text="Укажите владельца товара", blank=True,
                              null=True, on_delete=models.SET_NULL, related_name="Products")

    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")

    def __str__(self):
        return f"{self.name}, {self.category}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['name', 'category', 'price_per_purchase']

        permissions = [
            ("change_is_published", "Can change product publish status"),
            ("change_description", "Can change product description"),
            ("change_category", "Can change product category"),
        ]


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Contact(models.Model):
    country = models.CharField(max_length=200, verbose_name="Страна")
    INN = models.CharField(max_length=50, verbose_name="ИНН")
    address = models.CharField(max_length=200, verbose_name="Адрес")

    def __str__(self):
        return f"{self.country}, {self.INN}, {self.address}"

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"


class ProductVersion(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, verbose_name="Продукт",
                                related_name="product_versions")
    version = models.PositiveIntegerField(verbose_name="Номер версии")
    version_name = models.CharField(max_length=150, verbose_name="Название версии")
    is_active = models.BooleanField(verbose_name="Признак текущей версии", default=False)

    def __str__(self):
        return f"{self.product.name}, версия {self.version} | {self.is_active}"

    class Meta:
        verbose_name = "Версия продукта"
        verbose_name_plural = "Версии продуктов"

catalog/forms.py
from django import forms
from django.forms import HiddenInput

from catalog.models import Product, ProductVersion


class ProductBaseForm(forms.ModelForm):
    forbidden_words = (
        "казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар")

    def clean_name(self):
        return self.__validate_by_forbidden_words(self.cleaned_data.get('name'), "Имя")

    def clean_description(self):
        return self.__validate_by_forbidden_words(self.cleaned_data.get('description'), "Описание")

    def __validate_by_forbidden_words(self, cleaned_data, field_name_exception_message):
        prepare_data = cleaned_data.strip().lower()
        for forbidden in self.forbidden_words:
            if forbidden in prepare_data:
                raise forms.ValidationError(
                    f"{field_name_exception_message} не должно содержать запрещенные слова '{forbidden}'!")
        return cleaned_data


class ProductForm(ProductBaseForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['owner'].widget = HiddenInput()


class ProductModeratorForm(ProductBaseForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')


class ProductVersionForm(forms.ModelForm):
    class Meta:
        model = ProductVersion
        fields = '__all__'

    def clean_is_active(self):
        cleaned_data = self.cleaned_data.get('is_active')
        # ver = self.cleaned_data.get('version')
        # if cleaned_data:
        #     data = ProductVersion.objects.filter(product=self.instance.product, is_active=True).exclude(version=ver)
        #     if data.exists():
        #         print("raise")
        #         raise forms.ValidationError("Для данного продукта уже есть активная версия!")

        return cleaned_data

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError, PermissionDenied
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, TemplateView, UpdateView, DeleteView

from catalog.forms import ProductForm, ProductVersionForm, ProductModeratorForm
from catalog.models import Product, Contact, ProductVersion, Category
from catalog.services import get_cached_category_list


class VersionMixin:
    """Mixin class для создания formset версии продукта для продукта.
        Примешивать в левой позиции"""

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormSet = inlineformset_factory(self.model, ProductVersion, form=ProductVersionForm, extra=1)
        if self.request.method == 'POST':
            version_form_set = VersionFormSet(self.request.POST, instance=self.object)
        else:
            version_form_set = VersionFormSet(instance=self.object)

        if 'formset' not in context_data:
            context_data['formset'] = version_form_set

        return context_data

    def form_valid(self, form):
        version_form_set = self.get_context_data()['formset']
        self.object = form.save()
        if version_form_set.is_valid():
            # Мне не нравится, но это способ рабочий
            # Почему-то через queryset, filter, count не работало
            # count = sum([1 for item in version_form_set.get_queryset() if item.is_active])
            # При добавлении новой группы (элемента) в formset правильнее оказалось использование cleaned_data
            count = sum([1 for item in version_form_set.cleaned_data if item.get('is_active')])
            if count > 1:
                for fs_form in version_form_set.forms:
                    if fs_form.instance.is_active:
                        fs_form.add_error("is_active",
                                          ValidationError("Одновременно может быть выбрана только одна версия"))

                return self.form_invalid(form, version_form_set)

            version_form_set.instance = self.object
            version_form_set.save()

        return super().form_valid(form)

    def form_invalid(self, form, version_form_set=None):
        context = self.get_context_data()
        context['form'] = form
        # данная проверка и version_form_set=None нужны, чтобы правильно отрабатывало при ошибке основной формы
        if version_form_set is not None:
            context['formset'] = version_form_set
        return self.render_to_response(context)


class ProductCreateView(LoginRequiredMixin, VersionMixin, CreateView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')
    login_url = reverse_lazy('users:login')
    form_class = ProductForm

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductListView(ListView):
    model = Product
    paginate_by = 4


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(LoginRequiredMixin, VersionMixin, UpdateView):
    model = Product
    form_class = ProductForm
    login_url = reverse_lazy('users:login')

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser or user == self.object.owner:
            return ProductForm
        elif user.has_perm("catalog.change_is_published") and user.has_perm(
                "catalog.change_description") and user.has_perm("catalog.change_category"):
            return ProductModeratorForm

        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')
    login_url = reverse_lazy('users:login')


class ContactPageView(TemplateView):
    template_name = "catalog/contact_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contacts"] = Contact.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"name={name}\nphone={phone}\nmessage={message}")
        return HttpResponseRedirect(reverse('catalog:contact_view'))


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_cached_category_list()

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EStore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_header.html'%}

<div class="container">
    {% block content %}
    {% endblock %}

    {% include 'catalog/includes/inc_footer.html' %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">Хотите удалить?</h3>
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="card-body">
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'catalog:blog_list' %}" class="btn btn-primary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                <h4 class="my-0 font-weight-normal">{{ object.slug }}</h4>
            </div>
            <div class="card-body">
                <img class="rounded mx-auto d-block img-fluid" src="{{ object.preview | make_media_path }}"
                     alt="Изображение продукта">
                <p class="mt-3 mb-4 text-start m-3">{{ object.body }}</p>
                <p class="mt-3 mb-4 text-start m-3">Дата создания: {{ object.created_at }}</p>
                {% if object.is_published %}
                <a class="btn btn-warning"
                   href="{% url 'catalog:blog_toggle_is_published' object.pk %}">Снять с публикации</a>
                {% else %}
                <a class="btn btn-success"
                   href="{% url 'catalog:blog_toggle_is_published' object.pk  %}">Опубликовать</a>
                {% endif %}
                <p class="mt-3 mb-4 text-start m-3">Просмотров: {{ object.views_count }}</p>
                <a href="{% url 'catalog:blog_update' object.pk %}" class="btn btn-primary">Редактировать</a>
                <a href="{% url 'catalog:blog_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блоги</h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:blog_create'%}">Создать</a>
    <div class="row text-center">
        <div class="row text-center">
            {% for blog in page_obj %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p class="mt-3 mb-4 text-start m-3">{{ blog.body|truncatechars:200 }}</p>
                        <p class="card-title pricing-card-title">{{ blog.created_at}} ₽</p>
                        <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                           href="{% url 'catalog:blog_detail' blog.pk %}">Подробнее</a>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div id="pages" align="center">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}

                <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endblock%}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html'%}
{% load custom_filters %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">EStore</h1>
    <p class="lead">EStore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="row text-center">
    <div class="row text-center">

        <h4 class="h4">Список категорий</h4>
        <table class="table table-striped table-bordered">
            <thead class="thead-light">
            <tr>
                <th scope="col">Наименование</th>
                <th scope="col">Описание</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td class="text-start">{{ object.name }}</td>
                <td class="text-start">{{ object.description }}</td>
            </tr>
            {% endfor%}
            </tbody>
        </table>
    </div>
</div>

{% endblock%}

catalog/templates/catalog/contact_list.html
{% extends 'catalog/base.html'%}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% for x in contacts %}
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{x.country}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{x.INN}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{x.address}}</td>
                        </tr>
                    </table>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message"
                                      placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

catalog/templates/catalog/contacts.html
{% extends 'base.html'%}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% for x in contacts %}
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{x.country}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{x.INN}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{x.address}}</td>
                        </tr>
                    </table>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">Хотите удалить?</h3>
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="card-body">
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-primary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">Цена {{ object.price_per_purchase}} ₽</h2>
                <img class="rounded mx-auto d-block img-fluid" src="{{ object.preview | make_media_path }}"
                     alt="Изображение продукта">
                <p class="mt-3 mb-4 text-start m-3">{{ object.description }}</p>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                {% if perms.catalog.change_is_published and perms.catalog.change_description and perms.catalog.change_category or user == object.owner %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_update' object.pk %}">Редактировать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% if object %}
    <h1 class="display-4">Обновите товар</h1>
    {% else %}
    <h1 class="display-4">Добавьте товар</h1>
    {% endif %}

</div>
<div class="row text-start">
    <form method="post" action="" class="row" enctype="multipart/form-data">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    {% if object %}
                    <h4 class="my-0 font-weight-normal">Форма для обновления товара</h4>
                    {% else %}
                    <h4 class="my-0 font-weight-normal">Форма для добавления нового товара</h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сохранить</button>
                    {% if object and user == object.owner %}
                    <a href="{% url 'catalog:product_delete' object.pk %}" class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Форма для редактирования версии товара</h4>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset %}
                    {{ form|crispy }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock%}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html'%}
{% load custom_filters %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">EStore</h1>
    <p class="lead">EStore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="row text-center">
    <div class="row text-center">
        {% for prod in page_obj %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ prod.name }}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">Цена {{ prod.price_per_purchase}} ₽</h2>
                    <p class="mt-3 mb-4 text-start m-3">{{ prod.description|truncatechars:100 }}</p>
                    <p class="card-title pricing-card-title">{{ prod.product_versions|get_active_version }}</p>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                       href="{% url 'catalog:product_detail' prod.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}

        <div id="pages" align="center">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock%}